# Generated by Django 3.1.6 on 2021-02-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Em Aberto'), ('BUSY', 'Em Processo'), ('SOLVED', 'Solucionado')], default='OPEN', max_length=7),
        ),
    ]
