# Generated by Django 3.1.6 on 2021-02-10 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register_api', '0005_auto_20210208_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='slug',
        ),
        migrations.AlterField(
            model_name='error',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='error',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email do usuário'),
        ),
    ]
