# Generated by Django 3.1.6 on 2021-02-20 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register_api', '0007_auto_20210220_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='last_modified_by',
        ),
        migrations.AlterField(
            model_name='bug',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
